### ISSUE TITLE
Not working anymore in firefox on linux

### ISSUE THREAD

**Issue by mgerhardy** [floooh/voxel-test#3]
=> App::StartMainLoop()
App::onFrame(): Switching to app state 'EnqueuePreload'
App::onFrame(): Switching to app state 'Preloading'
App::onFrame(): Switching to app state 'Init'
Could not create canvas: ?,:(,{"alpha":false,"depth":true,"stencil":true,"antialias":true,"premultipliedAlpha":false,"preserveDrawingBuffer":false,"preferLowPowerToHighPerformance":false,"failIfMajorPerformanceCaveat":false,"majorVersion":1,"minorVersion":0}

**Comment by mgerhardy** [comment]
it used to work fine a few days ago

**Comment by floooh** [comment]
I didn't change anything, I swear :P Oh wait, I did... I changed the canvas pixel format to RGBA8, and but it looks like when requesting the canvas the alpha is set to false. I'll look into it. Thanks for noticing and reporting :)

**Comment by floooh** [comment]
Hmm it looks like I uploaded some inbetween version, because that alpha:false shouldn't be there. I've updated the demos, if it is still broken, can you copy the content of the Javascript console? Sometimes there's more detailed error information from the browser. Thanks!

**Comment by floooh** [comment]
Argh, I assumed the whole time that this is the Oryol issue tracker ;) Will also upload a new voxel-test version right away :)

**Comment by floooh** [comment]
Ok, voxel-test also updated, there should be a new message in the text log like this above the GL renderer extension info:

```
emscDisplayMgr: alpha=1, depth=1, stencil=1, antialias=1
```

**Comment by mgerhardy** [comment]
works again for me - thanks for fixing
